CREATE TABLE roles
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles(role)
VALUES ('USER'),
       ('ADMIN');

CREATE TABLE users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(120) NOT NULL UNIQUE,
    password TEXT         NOT NULL,
    name     VARCHAR(120) NOT NULL,
    enabled  BOOL         NOT NULL DEFAULT FALSE
);

CREATE TABLE users_roles
(
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_on_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_users_roles_on_roles FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE verification_token
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255)                NOT NULL,
    user_id     INTEGER                     NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_verification_token_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);
