CREATE TABLE roles
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles(role)
VALUES ('USER'),
       ('ADMIN');

CREATE TABLE users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(120) NOT NULL UNIQUE,
    password TEXT         NOT NULL,
    name     VARCHAR(120) NOT NULL,
    enabled  BOOL         NOT NULL DEFAULT TRUE
);

CREATE TABLE users_roles
(
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_users_roles_roles FOREIGN KEY (role_id) REFERENCES roles (id)
);

